function zeroliftalpha = importfileZeroLiftAlpha(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ZEROLIFTALPHA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  ZEROLIFTALPHA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  zeroliftalpha = importfile("/Users/tysonc/Library/CloudStorage/OneDrive-CalPoly/AERO 444/drag_buildup/digitzation/zero-lift-alpha.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jan-2025 14:01:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "Lambda", "Lambda_1"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
zeroliftalpha = readtable(filename, opts);

%% Convert to output type
zeroliftalpha = table2array(zeroliftalpha);
end