function dragtaildelta2 = importfiledrag_tail_delta2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DRAGTAILDELTA2 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  DRAGTAILDELTA2 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  dragtaildelta2 = importfile("/Users/tysonc/Documents/GitHub/433_design_problem/drag_buildup/derivatives/drag_tail_delta2.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Feb-2025 00:00:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "tc_30", "tc_21", "tc_12"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dragtaildelta2 = readtable(filename, opts);

%% Convert to output type
dragtaildelta2 = table2array(dragtaildelta2);
end