%% Flap Sizing Program
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%
%performs flap sizing based on Young, A.D., "The Aerodynamic Characteristics of Flaps", Aeronautical Research Council Reports and
%Memoranda, R&M 2622, 1953.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%
%first input a target CL, CL generated by wing, flap span ratio b_f/b
%program varies flap deflection to find chord ratio 
%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%
%UPDATES TO BE MADE
%automatically obtain CL generated by wing based on speed, altitude, alpha
%by using MainFunction.m and developing takeoff model
%%%%%%%%%%%%%%%%%%%%%%%%%%

%housekeeping 
clc; clear; close all;

%inputting required values
CL_target = ;           %input targeted CL for wing and flaps combination
CL_W = ;                %input CL generated by the wing at conditions
bf_b = 0.55;             %input ratio of flap span to wing span

