function DragBuildUp = importfileTEST(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DRAGBUILDUP = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DRAGBUILDUP = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DRAGBUILDUP = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DragBuildUp = importfile("C:\Users\bravo_4e3\OneDrive\Desktop\Cal Poly\AERO 444 - Aircraft Design II\DragBuildUp.xlsx", "Input Equations", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Jan-2025 14:24:23

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["string", "string", "double", "categorical"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName4"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName3", "TreatAsMissing", '');

% Import the data
DragBuildUp = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DragBuildUp = [DragBuildUp; tb]; %#ok<AGROW>
end

end