function planeData = importplaneData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PLANEDATA1 = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  PLANEDATA1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  PLANEDATA1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  planeData1 = importfile("C:\Users\bravo_4e3\OneDrive - Cal Poly\AERO 435 - Design I\Design Project\planeData.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Oct-2024 15:05:57

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["PlaneName", "MTOWlb", "W_elb", "Sft2", "AR", "V_sfts", "V_maxfts", "PowerOfEnginehp", "S_TOFLft", "S_L"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "PlaneName", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "PlaneName", "EmptyFieldRule", "auto");

% Import the data
planeData = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    planeData = [planeData; tb]; %#ok<AGROW>
end

end