function B111AE6 = importB111AE6(filename, dataLines)
%IMPORTFILE Import data from a text file
%  B111AE6 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  B111AE6 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  B111AE6 = importfile("C:\Users\bravo_4e3\OneDrive\Desktop\Cal Poly\AERO 444 - Aircraft Design II\B11-1A_E6.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jan-2025 21:53:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "KVsTrailingEdgeAngle"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
B111AE6 = readtable(filename, opts);

%% Convert to output type
B111AE6 = table2array(B111AE6);
end