function dragF = importfiledrag_F(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DRAGF = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  DRAGF = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  dragF = importfile("/Users/tysonc/Documents/GitHub/433_design_problem/drag_buildup/derivatives/drag_F.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Feb-2025 14:43:53

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "Curve1"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dragF = readtable(filename, opts);

%% Convert to output type
dragF = table2array(dragF);
end